### ISSUE TITLE
K# syntax

### ISSUE THREAD

**Issue by Dotnet-And-Happiness** [AaronSong321/KSharp#1]
How the k# syntax looks?

**Comment by AaronSong321** [comment]
Refer to KSharp/KSharpCompiler/Grammar. It's written in Antlr4.

**Comment by Dotnet-And-Happiness** [comment]
I'm not very good at antlr grammar
Maybe show simple hello world?

**Comment by AaronSong321** [comment]
using System
using System.Collections.Generic

namespace Example // top-level namespace, no brackets needed
class Program // default access of untested class is public
{
private static Main(args:string[]) // somehow like Kotlin :Unit type annotator is optional
{
    Console.WriteLine("Hello, world!");
}
}

**Comment by AaronSong321** [comment]
For more complex type definitions, refer to  KSharp/KSharpCompiler/Grammar/Magic.ks,  KSharp/KSharpCompiler/Grammar/Giraffe.ks
